### ISSUE TITLE
Search bar in chinesse

### ISSUE THREAD

**Issue by jlmcr87** [ingbrzy/MA-XML-7.0-SPANISH#106]
Redmi note 2 with 6.3.10/11.

This search bar is in chinesse. Please translate it.

![screenshot_2016-03-13-09-27-13_com miui home](https://cloud.githubusercontent.com/assets/4967467/13727726/69f6e82e-e8fe-11e5-9c89-34133c67c7ae.png)

**Comment by silver-james** [comment]
Ve a Ajustes -> Aplicaciones instaladas -> Búsqueda -> Borrar datos y después, reinicia el teléfono.

Go to Settings -> Installed applications -> Search -> Clear data. After that, reboot your phone.
