### ISSUE TITLE
Force close on hennessy 6.3.17

### ISSUE THREAD

**Issue by ssergiio** [ingbrzy/MA-XML-7.0-SPANISH#107]
Thanks for the hard work! I'm getting FC on Settings-Lockscreen and password-Password and fingerprint when I try to enter it. I'm using Redmi Note 3 (MTK). I know that I'm not the only one facing this problem on RN3.

**Comment by ssergiio** [comment]
Para ser exactos no aparece el forzar cierre en ningun momento, es mas un crasheo. Se queda la pantalla en blanco sin pedir contraseña y vuelve a la pantalla anterior.

**Comment by silver-james** [comment]
¿Has probado a cambiar el idioma a inglés y volver a entrar? Para descartar que sea cosa de la rom

**Comment by ssergiio** [comment]
Si, lo probé despues de que @ingbrzy me pidiera hacerlo y efectivamente en inglés el problema no existe.

**Comment by silver-james** [comment]
En principio no hemos tocado ninguna traducción de esa parte, echaremos un vistazo a ver que encontramos

**Comment by ssergiio** [comment]
De acuerdo, muchas gracias!

**Comment by jamflux** [comment]
Es un problema de los archivos que usan de español al momento de compilar la ROM. Quién puede dar la solución sería  @ingbrzy.
Please, fix fc on settings when going to use fingerprint. @ingbrzy. Thank you.

**Comment by ingbrzy** [comment]
post FC log here..

**Comment by giltros1** [comment]
log

![photo_2016-03-19_19-14-02](https://cloud.githubusercontent.com/assets/17952627/13900456/1d05469c-ee07-11e5-989e-b192eb0abd39.jpg)

![photo_2016-03-19_19-13-57](https://cloud.githubusercontent.com/assets/17952627/13900461/2a02ed18-ee07-11e5-926b-e6f2f1ee7ac1.jpg)

![photo_2016-03-19_19-13-54](https://cloud.githubusercontent.com/assets/17952627/13900463/32818e9a-ee07-11e5-8cba-4daca27222ba.jpg)

**Comment by ingbrzy** [comment]
fixed for next version..

**Comment by giltros1** [comment]
ok

**Comment by ssergiio** [comment]
Thank you so much! I got some crashes on the new fingerprint app locking feature too that got resolved rebooting the device.
