### ISSUE TITLE
Error en ajustes de alarmas

### ISSUE THREAD

**Issue by asirena** [ingbrzy/MA-XML-7.0-SPANISH#108]
En la opción "Repetición de las alarmas" falta la opción de 1 minuto (en inglés tenemos 1minute, 5, 10, 15, 20, 25, y 30).

En la opción "Silenciar automáticamente" falta la opción de 1 minuto (en inglés tenemos , Never, 1minute, 5, 10, 15, 20, 25, y 30). 

En esta última opción además, por faltar esta elección, cuando la miramos desde fuera aparece el subtexto "Las alarmas se silenciarán tras X minutos"; siendo X la opción previa a la realmente seleccionada (por ejemplo si seleccionamos "20 minutos", en el texto aparecerá "15 minutos"). No he llegado a comprobar si se desactiva a los minutos seleccionados o a los minutos que aparecen en ese texto.

Por favor, espero lo puedan corregir pronto.

**Comment by silver-james** [comment]
¿Qué versión estás utilizando? En la última disponible no ocurren los problemas comentados

![photo27301982275479507](https://cloud.githubusercontent.com/assets/6978992/13913254/37a62194-ef45-11e5-948a-eac0b82f4f63.jpg)
![photo27301982275479506](https://cloud.githubusercontent.com/assets/6978992/13913259/42febcfe-ef45-11e5-91a8-910ee5c657a3.jpg)

**Comment by asirena** [comment]
Pues tengo la versión 6.3.3 (última disponible en http://en.miui.com/download-274.html). 

Pero ya veo que en esa página se retrasan a la hora de sacar las actualizaciones y ya hay un par de versiones posteriores.

Gracias!

**Comment by silver-james** [comment]
Esas las traduce directamente Xiaomi. Las ROM traducidas por nosotros se encuentran aquí http://xiaomi.eu/community/forums/miui-weekly-rom-releases.103/
