### ISSUE TITLE
Errores y mejoras de traducción

### ISSUE THREAD

**Issue by asirena** [ingbrzy/MA-XML-7.0-SPANISH#109]
Les dejo a continuación algunos errores y mejoras en la traducción al español.

* Teléfono > Configuración > Redial automatically
Rellamada automática

* Teléfono > Configuración > ANSWERING
Llamada entrante

* Teléfono > Configuración > Marcador
Llamada saliente

* Ajustes > Wi-Fi > Ajustes avanzados > Botón WPS push
Pulsación de botón WPS.
(dentro en el título también)

* Ajustes > Wi-Fi > Ajustes avanzados > Entrada de PIN WPS 
(dentro en el título pone Botón WPS push en lugar de "Entrada de PIN WPS")

* Sonido & vibración > Vibrar
Vibración

* Sonido & vibración > Tono de llamada & vibrar
Tono de llamada y vibración

Y en general se hace mucho uso del símbolo '&' el cual muchas personas, mayores sobre todo, no conocen y achacan a errores de traducción. Es recomendable reemplazarlos todos por la 'y' del idioma español ya que ocupa el mismo espacio en pantalla y es entendible por el 100% de los usuarios. Por ejemplo:
* Tarjetas SIM & redes móviles
* Anclaje de red & zona wifi
* Colores & contraste
* Sonido & vibración
* Tono de llamada & notificaciones
* Tono de llamada & vibrar
* Fecha & hora
* Rendimiento & batería
* Auriculares & efectos de audio
* etc.

Saludos.

**Comment by silver-james** [comment]
Le comento lo mismo que en el issue #108 ¿Qué versión de la ROM está utilizando? En ninguna de las traducciones que comenta se usa "&" en lugar de "y"
![photo27301982275479508](https://cloud.githubusercontent.com/assets/6978992/13913347/1efe21e0-ef46-11e5-85a1-bfa0b2522b5d.jpg)

**Comment by asirena** [comment]
La 6.3.3. Como dije en la #108 ya veo que existen un par de versiones posteriores.

¿Los otros fallos indicados también están solucionados en la última version (6.3.17)?

Muchas gracias!

**Comment by silver-james** [comment]
En la de xiaomi.eu sí http://xiaomi.eu/community/forums/miui-weekly-rom-releases.103/ Las capturas mostradas son de esa versión.
Desde aquí solo te podemos ayudar con las ROM de xiaomi.eu. Si utilizas las que se encuentran en la página de MIUI, tienes que ponerte en contacto con ellos a través de su foro de soporte http://en.miui.com/forum.php?forumlist=1

**Comment by asirena** [comment]
Tenía entendido que ellos utilizan las traduciones (al menos al español) hechas aquí para la ROM "Global". Lo que no sabía era que existían versiones más actualizadas.

Actualizaré a la última versión. Gracias por todo.
