### ISSUE TITLE
Es la primera vez que uso esto

### ISSUE THREAD

**Issue by Infante007** [ingbrzy/MA-XML-7.0-SPANISH#110]
Vengo a informar que no hay traduccion en dos sitios que yo vea MIUI 7.3 by xiaomi.eu 6.3.24 beta
1- en seguridad y al darle a datos no hay nada en español y antes que yo recuerde estaba traducido.
2.en galeria antes estaba puesto en español y ahora esta en ingles
gracias

**Comment by Infante007** [comment]
No hay nadie que me ayude en este problema?
De xioami.eu me reportaron aquí,si puedo hacer algo mas....
gracias

**Comment by jamflux** [comment]
Hola infante. Aún no he entendido dónde no hay traducción. La traducción de la app seguridad, la más reciente ya la he agregado. Cuando hablas de datos no sé dónde es. Revisada la app galería y no he encontrado nada en inglés.
Las traducciones a español sólo están en las ROMs de xiaomi.eu, instala siempre las versión más actualizada.
No nos has dicho que dispositivo tienes.
Pon unas capturas o da la ruta especifica para ayudarte.

**Comment by Infante007** [comment]
Perdona @jamflux es la primera vez que pregunto aqui  y no sabia como iba.
Tengo un mi3 con la ultima europea instalada:
![screenshot_2016-03-28-14-07-47_com android settings](https://cloud.githubusercontent.com/assets/18089036/14078664/ff9792e8-f4f7-11e5-8188-48aacec91597.png).
Donde te comento el no estar traducido es en la galeria:
![screenshot_2016-03-28-14-07-57_com miui gallery](https://cloud.githubusercontent.com/assets/18089036/14078709/5db59a5a-f4f8-11e5-8fc6-2eb3532ab084.jpg)
y en la aplicacion de seguridad-datos:
![screenshot_2016-03-28-14-08-15_com miui securitycenter](https://cloud.githubusercontent.com/assets/18089036/14078723/7831ac0c-f4f8-11e5-86be-1162f0d1786b.png)
![screenshot_2016-03-28-14-08-18_com miui securitycenter](https://cloud.githubusercontent.com/assets/18089036/14078730/7fd53fd2-f4f8-11e5-9968-9674283c4d0f.png)
![screenshot_2016-03-28-14-08-27_com miui securitycenter](https://cloud.githubusercontent.com/assets/18089036/14078733/83a5d96e-f4f8-11e5-88cc-1f633997af60.png)
![screenshot_2016-03-28-14-08-31_com miui securitycenter](https://cloud.githubusercontent.com/assets/18089036/14078736/8695d4e4-f4f8-11e5-97c0-35a63137dfef.png)
![screenshot_2016-03-28-14-08-40_com miui securitycenter](https://cloud.githubusercontent.com/assets/18089036/14078738/889e8600-f4f8-11e5-9616-98f72d472267.png)
![screenshot_2016-03-28-14-08-49_com miui securitycenter](https://cloud.githubusercontent.com/assets/18089036/14078740/8abea47e-f4f8-11e5-9744-1e3526cff0c3.png)
La instalacion siempre desde recovery,cualquier cosa mas te paso lo que me pidas
gracias

**Comment by silver-james** [comment]
@Infante007 La parte de Seguridad - Datos, como dices, está sin traducir. Nos pondremos con ello.
En cuanto a la Galería ocurre algo curioso. En mi Redmi Note 2 solo aparecen dos pestañas pero si que están traducidas (lo traduje hace un par de semanas) 
![photo27301982275479509](https://cloud.githubusercontent.com/assets/6978992/14079105/7f395aec-f4fb-11e5-8364-545ddbefd59e.jpg)

**Comment by Infante007** [comment]
Pues @silver-james y @jamflux aun asi os lo  agradezco un monton, cuando puedas hacerlo y antes que todo disfrutar de la vida.
un saludo y gracias adelantadas.
Pd. yo creo que lo de la galeria es que como esta conectado online cambiara la traduccion automaticamente, es lo mismo que pasaba con los temas , en xioami.es lo ponian en español, pero en cuanto se conectaba al servidor se cambiaba al ingles automaticamente.(es mi opinion)

**Comment by jamflux** [comment]
Listo @Infante007. Nos pondremos a ello.
Si todo se da en la próxima actualización queda todo al pelo ;)

**Comment by Infante007** [comment]
Muchas gracias @jamflux , se agradece vuestro trabajo.esperando la siguiente actualizacion
un abrazo

**Comment by silver-james** [comment]
@Infante007 Ya he traducido una gran parte de Seguridad, falta otra parte que se queda pendiente porque no me da tiempo para la ROM de esta semana. Si ves algún fallo o traducción mejorable, no dudes en comentarlo

**Comment by Infante007** [comment]
Muchas gracias @silver-james ,,ayudare en lo que pueda ,ya te aviso por aqui si veo fallo o alguna otra cosa.
Y otra vez muchas gracias

**Comment by jamflux** [comment]
@silver-james tú ayudas en la elaboración de las ROMs xiaomi.eu?  Si es así podría pedirte ayuda en algunas cosas ya que tengo una línea de ROMs para el Redmi Note 3 MTK.

**Comment by Infante007** [comment]
No, lo siento @silver-james no ayudo en la xiaomi.eu,un pena que no pueda ayudarte 
lo siento

**Comment by jamflux** [comment]
Seguridad arreglada!
De galería estuve buscando y no encontré nada.
Imagino que está amarrada la traducción con cloud service.
Seguiré en el etema hasta que de con el chiste.

**Comment by Pab69** [comment]
Hola, yo tengo MIUI 7.3 6.3.24 Xiaomi.eu Beta en el Mi4c y también me sale en inglés los settings de Datos, en cambio la Galería sale en castellano.
Luego está lo de la barra de búsqueda que se quedan palabras en chino...

Otro tema en inglés que acabo de ver es en Ajustes/Aplicaciones de sistema/Galería, los 4 primeros parámetros salen inglés, el resto en castellano. Ajustes/Aplicaciones de sistema/ Mi Cloud/Galería, ocurre lo mismo, los 4 primeros están en inglés... 

Por cierto, tenía MIUI 7 multi eu y se me actualizó automáticamente a la que he puesto arriba, es normal que se pueda y se siga actualizando con Xiaomi.eu Beta-semanales? Se habrá bloqueado el Bootlaoader? 

Saludos!

**Comment by jamflux** [comment]
Todo está corregido, excepto el apartado de galería. Xiaomi.eu no actualiza las ROMs via updater.
Si en seguridad puedes ir al apartado permisos, acceso root y ni te sale nada en chino sino en inglés como advertencia es porque sigue desbloqueado. Saludos.




Enviado desde mi teléfono MiEl Pab69 <notifications@github.com>, 21/4/2016 13:19 escribió:Hola, yo tengo MIUI 7.3 6.3.24 Xiaomi.eu Beta en el Mi4c y también me sale en inglés los settings de Datos, en cambio la Galería sale en castellano.
Luego está lo de la barra de búsqueda que se quedan palabras en chino...

Otro tema en inglés que acabo de ver es en Ajustes/Aplicaciones de sistema/Galería, los 4 primeros parámetros salen inglés, el resto en castellano. Ajustes/Aplicaciones de sistema/ Mi Cloud/Galería, ocurre lo mismo, los 4 primeros están en inglés... 

Por cierto, tenía MIUI 7 multi eu y se me actualizó automáticamente a la que he puesto arriba, es normal que se pueda y se siga actualizando con Xiaomi.eu Beta-semanales? Se habrá bloqueado el Bootlaoader? 

Saludos!

**Comment by Pab69** [comment]
Ok, gracias por mejorar MIUI 7!!!

Es curioso lo de la actualización, te aseguro que tenía instalada de la tienda: xiaomi.eu_multi_libra_5.10.8_v7-5.1 y se me actualizó a MIUI 7.3 6.3.24 Xiaomi.eu Beta, y hace unos días me saltó una nueva actualización: Herramientas/Actualizaciones, MIUI 6.14.24 Semanal.

Ahora tengo desactivado Actualizar automáticamente y no hubiera aceptado la actualización anterior de haber sabido lo del tema del Bootloader.

En Seguridad/Permisos/Acceso root, puedo entrar y está todo en castellano pero no tengo root, lo sé porque intenté instalar el TWRP y SuperSU vía GApps y no pude, luego lo comprobé con Root Checker.

Pues espero como dices no tener el bootloader bloqueado porque sí que me gustaría más adelante rootearle...

**Comment by Infante007** [comment]
Muchas gracias @jamflux .

**Comment by Pab69** [comment]
@jamflux Tenías razón vía Updater actualiza a miui libra mam global.
 Parece que sigue desbloqueado.

Saludos!

**Comment by jamflux** [comment]
Corregidos los errores de traducción para la próxima entrega de la ROM .eu.

**Comment by Infante007** [comment]
gracias @jamflux ,eres un maquina
un saludo
