### ISSUE TITLE
Barra pemanente de busqueda en menú de notificaciones y accesos rapidos

### ISSUE THREAD

**Issue by gastt88** [ingbrzy/MA-XML-7.0-SPANISH#112]
Hola. 
Mi móvil es un Mi4 con versión 6.3.31 beta

Existe un error de traducción (mejor dicho, falta de traducción) en la nueva barra persistente de busqueda que se encuentra al deslizar hacia abajo la cortina de notificaciones/accesos rápidos 

Gracias ,saludos
![screenshot_2016-04-01-23-43-01_com quoord tapatalkpro activity](https://cloud.githubusercontent.com/assets/18225328/14224520/cfac3b00-f89f-11e5-9528-fda7fc7bbdfd.png)

**Comment by Infante007** [comment]
Por lo que parece la traducción la lleva @silver-james ,pero tiene mas trabajos y tarda en responder.
Ya cuando se pase te repondera.

**Comment by Infante007** [comment]
hola @gastt88 ayer actualice a la version eu 6.4.7 y por lo que vi en su foro no es tema de traduccion .
tienes que ir a aplicaciones instaladas y buscar la aplicacion busqueda ,eliminar datos, reinicias y ya esta en español.

**Comment by JS67** [comment]
Hola Infante007 he probado lo que dices de la barra de busqueda en chino y funciona!!!...pero....al cabo de unas cuantas busquedas, vuelve al chino, como se puede fijar una vez cambiado???
Saludos y Gracias

**Comment by Infante007** [comment]
Si tienes razon ,pues es dificil, son temas que al conectarse el buscador a internet se cambia en automatico.
No se si tendra solucion ,no se si @silver-james sabra algo mas ,yo ni idea
sorry

**Comment by JS67** [comment]
Muchisimas gracias por tu rapida respuesta!!!
Aparte he reportado algunos fallos que veo en la traducción (frases sin
traducir), a ver si entre todos lo arreglamos.
Gracias y saludos,

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-04-09 20:26 GMT+02:00 Infante007 <notifications@github.com>:

**Comment by jamflux** [comment]
Éste asunto de la barra con sugerencias chinas no va con la traducción en sí, tiene que ver en el apartado de la aplicación como tal, la ROM en sí. May be @ingbrzy  can do some in this issue, chinese suggestions on searh bar.

**Comment by jamflux** [comment]
Cierro el caso porque no se puede hacer mayor cosa cuando no se trata de traducción.
En futuras actualizaciones puede que el maestro @ingbrzy lo solucione, ya que es un problema de la app en sí, mas no de traducción. Habrá que hacerle un parche a la app.
Saludos.
