### ISSUE TITLE
Tradusccion

### ISSUE THREAD

**Issue by moca1974** [ingbrzy/MA-XML-7.0-SPANISH#114]
Hola, en el apartado seguridad, hay varias cosas sin traduccion, como uso de datos y una linea en el apartado de permisos.
Gran trabajo, gracias.

**Comment by jamflux** [comment]
Trabajaremos en ello. Gracias.

**Comment by jamflux** [comment]
Arreglado, tardé un par de días con las traducciones... pff.
Cierro el caso.

**Comment by Infante007** [comment]
Muchas gracias por tu trabajo @jamflux
