### ISSUE TITLE
Fallo al crear nueva alarma personalizada y fallo de traducción.

### ISSUE THREAD

**Issue by Chinosandman** [ingbrzy/MA-XML-7.0-SPANISH#115]
Al añadir una alarma e intentar configurar los días en el menú "Repetir" y escoger la opción personalizado, en vez de dejarte elegir los días que quieres que la alarma suene, se pone solo en "lun,mar, mie, jue, vie".
Si cambiamos el idioma a cualquier otro (probado en inglés y francés), funciona correctamente, por lo cual deduzco que será fallo de la traducción.

Aparte hay otro fallo de traducción al elegir la alarma de lunes a viernes. Se pone en: "Legal off day".
También hay un apartado que esta en "delete after goes off" al añadir una alarma. 

Salu2.

**Comment by Infante007** [comment]
Si tienes razón es un bug, y no da la opción de poder poner la alarma

**Comment by jamflux** [comment]
Solucionado, era bug de la traducción.
Traduje todo de nuevo usando los xmls más recientes (6.4.14)
Cierro el caso, En la próxima actualización se verá el cambios.
