### ISSUE TITLE
Fallo en el calendario

### ISSUE THREAD

**Issue by tomynokker** [ingbrzy/MA-XML-7.0-SPANISH#116]
En el calendario cuando quieres acceder al vista mensual, se pone en vista del dia pero con todos los recodatorios del dia. Lo suyo seria la vista de todo el mes.

**Comment by Infante007** [comment]
No entiendo @tomynokker, yo tengo un mi3 y va perfecto. Pon unas capturas

**Comment by tomynokker** [comment]
En el recuadro verde se tendria que ver el mes entero
![screenshot_2016-04-15-16-43-57_com android calendar_1460731553454_1460731707527](https://cloud.githubusercontent.com/assets/14758226/14565234/5e6ea532-032a-11e6-8141-eaf812b5eaaf.jpg)
![screenshot_2016-04-15-16-43-44_com android calendar_1460731617586](https://cloud.githubusercontent.com/assets/14758226/14565276/9711b4b0-032a-11e6-934a-82821f3935d5.jpg)

**Comment by Infante007** [comment]
no te puedo mandar capturas ahora mismo, pero a mi me va perfecto.
que movil tienes y que version de rom.

**Comment by jamflux** [comment]
Lo sentimos, no es problema de traducción.
De todos modos va bien la app, no encontré ese problema.
@tomynokker, trata de borrar la caché de la app o los datos, sino, hacer instalación limpia de la ROM.
Siempre pon la ROM más actualizada.
Saludos;)

**Comment by tomynokker** [comment]
Perdona fallo mio. Redmi Note 3G v 6.4.7 pero este fallo ya hace unas versiones que lo tiene pero no lo he reportado antes por falta de tiempo. Te pongo una captura que he descargado de internet para que veas a lo que me refiero. Asi tendria que verse mas o menos.
![144117wfrfok27k5t2ofpk](https://cloud.githubusercontent.com/assets/14758226/14569742/de6ce13e-0340-11e6-8acb-34a914cf8f1c.jpg)

**Comment by deivids84** [comment]
Però esto se puede ajustar tocando la parte de abajo y subes o bajas el dedo. Hay la opcion de vista de més o semana.

**Comment by tomynokker** [comment]
Vaya tienes razón , lo siento. Ni lo habia provado.
