### ISSUE TITLE
Errores en app Seguridad

### ISSUE THREAD

**Issue by asirena** [ingbrzy/MA-XML-7.0-SPANISH#117]
En la versión 6.4.21 recien instalada:

* en la pantalla resumen del Limpiador (una vez se han tomado las acciones requeridas): "Take the following actions to get the most out of your device." sin traducir.

* en Batería: "pefiles de batería" está en minúscula.

* al Optimizar, la cache no muestra el contenido de la variable, sino el nombre de la misma "@ String / memory_check_content_none".

* en Permisos las opciones con los textos "Notificar" y "Negar" son preferibles dejarlas como "Preguntar" y "Denegar", quedan mucho más correctas ya que una notificación no tiene porqué dar opción a nada.

* al establecer Permisos a aplicaciones, seleccionando "Notificar", cuando una app (en el ejemplo WhatsApp) intenta acceder a un recurso (en el ejemplo la cámara) el texto contiene varios errores y está desordenado: "Whatsapp trata de La aplicación podrá acceder a la cámara." cuando debería decir algo como "La aplicación Whatsapp está intentando acceder a la cámara."

* en Permisos: "Acceso raíz" es incorrecto, debe ser "Acceso root".

Otros errores de la 6.4.14 veo que ya han sido corregidos. Saludos.

**Comment by jamflux** [comment]
Hola @asirena gracias por los comentarios de los errores que aún quedan, con cada actualización pueden surgir más.
Te pido un favor, puedes colaborarnos en ese tema si quieres y puedes, subí el archivo de traducción http://www2.zippyshare.com/v/n3OvJ3ie/file.html
puedes realizarle los cambios que veas convenientes y así tan pronto lo hagas publico en el repositorio original. El archivo se puede editar con notepad ++ y subirlo nuevamente a zippyshare.
Gracias.

**Comment by asirena** [comment]
Gracias. He modificado "acceso raíz" / "acceso a la raíz" en varios sitios, "Notificar" y "Negar", y "pefiles de batería".

No encuentro las otras cadenas en el fichero, y sin embargo se puede comprobar como en el teléfono se muestran así (puedo subir captura si es necesario). Tal vez se encuentren en otros ficheros.

Dejo el fichero con los cambios indicados (no todos los reportados) aquí: http://www42.zippyshare.com/v/4XcCdghN/file.html



PD: Permitir que cualquier usuario pueda modificar los ficheros puede generar bastantes errores. Aun sin tener mala intención, en diferentes países el español tiene matices muy diferentes y lo que para unos es correcto para otros puede sonar muy extraño o incluso mal. Solo es una opinión.

**Comment by jamflux** [comment]
Corregidos errores para la próxima entrega de la ROM .eu

**Comment by asirena** [comment]
Gracias!
