### ISSUE TITLE
Error en app Tiempo

### ISSUE THREAD

**Issue by asirena** [ingbrzy/MA-XML-7.0-SPANISH#118]
"Rayos UVA" no es correcto (es lo que se toma para ponerse moreno), debe cambiarse a "Índice UV" que es la medida meteorológica de la radiación ultravioleta. 

https://es.wikipedia.org/wiki/%C3%8Dndice_UV

**Comment by jamflux** [comment]
Corregido, de nuevo: ¡gracias!
