### ISSUE TITLE
Errata en apartado Uso de la batería

### ISSUE THREAD

**Issue by josepitxy** [ingbrzy/MA-XML-7.0-SPANISH#120]
En el apartado de uso de la batería pone "Celda de poder" cuando debería poner "Teléfono inactivo" o "Dispositivo inactivo" o "Teléfono en espera" o "Dispositivo en espera"

**Comment by asirena** [comment]
La opción "Telefono inactivo" ya existe aparte de esta. En "Celda de poder", dentro indica: "Batería utilizada por la radio".

En inglés es "Cell standby". No se a que hace referencia...

**Comment by josepitxy** [comment]
Quería decir que "Cell standby" es "Teléfono en espera"

**Comment by asirena** [comment]
SI, pero además existe la opción "Phone idle". Es decir, dos opciones muy similares, y además mezclando "phone" con "cell" (de celda del mapa de cobertura, no de celular o teléfono móvil).

Imagino que uno será "Dispositivo inactivo" (Phone idle, mejor indicar dispositivo que teléfono) haciendo referencia a que no se está utilizando. y el otro "Teléfono en espera" (Cell standby) haciendo referencia a que no se está realizando/recibiendo ninguna llamada.

**Comment by josepitxy** [comment]
El idle es es teléfono inactivo y el standby supongo q será en espera d llamadas y datos
Con respecto a las llamadas que puse de llamada a 3 sigue apareciendo al rato de estar hablando por teléfono
El 23/4/2016 13:34, asirena <notifications@github.com> escribió:SI, pero además existe la opción "Phone idle". Es decir, dos opciones muy similares, y además mezclando "phone" con "cell" (de celda del mapa de cobertura, no de celular o teléfono móvil).

Imagino que uno será "Dispositivo inactivo" (Phone idle, mejor indicar dispositivo que teléfono) haciendo referencia a que no se está utilizando. y el otro "Teléfono en espera" (Cell standby) haciendo referencia a que no se está realizando/recibiendo ninguna llamada.

**Comment by jamflux** [comment]
Corregidos errores para la próxima entrega de la ROM .eu
