### ISSUE TITLE
Error al realizar o recibir llamadas

### ISSUE THREAD

**Issue by josepitxy** [ingbrzy/MA-XML-7.0-SPANISH#121]
Al realizar o recibir una llamada normal, aparece en la pantalla "LLamada a 3"

**Comment by asirena** [comment]
He probado a hacerme una llamada y no me aparece nada de eso sino el nombre y la imagen del contacto. Y en llamadas perdidas lo mismo. ¿Como podría reproducirlo?

**Comment by josepitxy** [comment]
He vuelto a hacer los wipes dalvic y caché y ya se ha solucionado
