### ISSUE TITLE
Errores en app Teléfono

### ISSUE THREAD

**Issue by asirena** [ingbrzy/MA-XML-7.0-SPANISH#122]
En la app Teléfono, en ajustes, en la opción "Identificar números desconocidos", la aplicación falla y se cierra. Sospecho que puede deberse a la falta de traducción de los términos de uso o licencia (o a algun error relacionado con la misma) que intenta mostrar al lanzarse.

Ocurre exactamente lo mismo que ocurría versiones atras con la Galería de fotos. Y la solución es la misma: cambiar el idioma a inglés, aceptar los términos y volver a cambiar a español.

Una corregido el error anterior, existen otros 4 errores en este mismo apartado:

* al activar/desactivar "Identificar números desconocidos", los mensajes mostrados se encuentran sin traducir.

* en "Acerca de esta característica", el mensaje que muestra dice "Attention".

* en "Cuidado con los fraudes", el mensaje que muestra dice "Attention".
 
* en "Acerca de esta característica" y en "Cuidado con los fraudes", la explicación que se proporciona en estas opciones se encuentra en inglés.

Además, en algunas otras opciones como "Llamada en espera", "Restricción de llamadas" o "Identificador de llamadas", al entrar aparece un mensaje con el texto "Call settings", sin traducir.

**Comment by jamflux** [comment]
Aún no encuentro el error... no sé cuál app es ya que revisé la sugerida y no es... seguiré buscando...

**Comment by asirena** [comment]
Luego subo unas capturas de pantalla, para que puedas intentar reproducirlo. Un saludo.

**Comment by asirena** [comment]
Lo siento. No puedo volver a reproducir el error ya que lo solucioné de la forma que indico en el primer mensaje, por lo tanto no vuelve a intentar salir el mensaje de aceptación.

Lo pasos para reproducirlo son:
(0) Paso previo. Es necesario tener el teléfono configurado con idioma español.
(1) Ir a la app Teléfono
(2) Desplegar el menú (arriba en el circulo con tres puntos)
(3) Seleccionar "Ajustes"
(4) Seleccionar "Identificar números desconocidos"
(5) La aplicación se cierra. Debería aparecer un mensaje de aceptación, la primera vez que se entra. Volver a repetir los pasos (1-4) cambiando previamente el idioma a inglés para ver el mensaje y poder entrar.

Espero sea de ayuda.

**Comment by asirena** [comment]
He pedido a un amigo que siguiera los pasos para reproducir el fallo e hiciera las capturas.

Este es el mensaje que en español no llega a salir: http://oi65.tinypic.com/2lka9l3.jpg

Este el error que da si se intenta acceder con idioma español:  http://oi63.tinypic.com/2z7qy6u.jpg

En la segunda captura se aprecia que la aplicación no es Teléfono (yo la indiqué así ya que desde ella accedía al error), sino Páginas ¿amarillas?. 

Un saludo.

**Comment by Infante007** [comment]
Yo tambien lo tengo comprobado,tengo un mi3 con la ultima version eu.
Si me llama un numero desconocido y quiero ver la llamada me da FC.
No se si sera por el idioma .

**Comment by jamflux** [comment]
Buenas amig@s.
Yo tengo un Redmi Note 3 MTK y no me sale esa opción por más que la busque, imagino que es por el procesador...
Quien pueda que me pase las tres aplicaciones relacionadas para verle las configuraciones: Telecom.apk, IncallUI.apk y Contacts.apk dentro de las carpetas raíz /system/priv-apps o /system/apps.
Y si ven alguna que diga "identify unknown numbers" o algo parecido, también me la pueden pasar.
Subir a zippyshare que es más rápido y fácil de usar.

Imagino también que el FC se debe a la traducción que a mi no me pasa porque tal ajuste no existe en mi teléfono.
Saludos.

**Comment by jamflux** [comment]
@asirena @Infante007 espero que puedan subir esos archivos para poder encontrar el fallo, de lo contrario he de cerrar el caso porque no he encontrado el error en mi teléfono...

**Comment by asirena** [comment]
Esta tarde busco y subo los APKs solicitados. De todas formas en /system/priv-apps existe una app llamada YellowPage que sospecho debe ser la implicada por lo que puede verse en el error de la segunda captura (aunque el nombre no se ve completo es "Páginas amarillas").

Un saludo.

**Comment by jamflux** [comment]
Sip, manda esa también.
Actualicé el idioma de la última beta con los cambios que hice:
http://www.htcmania.com/showthread.php?t=1158989&page=35
Algunas capturas con los cambios hechos.
Hasta el viernes sale para todos, jeje.
Saludos.

**Comment by asirena** [comment]
Aqui estan: http://www99.zippyshare.com/v/wm7Zlei0/file.html

**Comment by jamflux** [comment]
Vale, las revisaré. Muchas gracias.



Enviado desde mi teléfono MiEl asirena <notifications@github.com>, 28/4/2016 8:47 escribió:Aqui estan: http://www99.zippyshare.com/v/wm7Zlei0/file.html

**Comment by asirena** [comment]
Gracias. 

Además en YellowPage ( https://github.com/ingbrzy/MA-XML-7.0-SPANISH/blob/master/Spanish/main/YellowPage.apk/res/values-es/strings.xml ) hay algunas cosas sin traducir como:
* líneas 21, 49, 230, 240, 287, 288, 295, 303, 312, y 314: RMB en lugar de EUR
* línea 293: símbolo del Yen
* línea 356: Attention

**Comment by jamflux** [comment]
Pues si puedes hacer esos cambios y subes el archivo sería mejor, al menos de la app yellowpage.
Saludos.

**Comment by asirena** [comment]
Ok. Aquí esta: https://github.com/ingbrzy/MA-XML-7.0-SPANISH/commit/3e94b11a99fbbb50999277762e0e48828f357236?diff=split

**Comment by jamflux** [comment]
listo, actualizado @asirena.
Faltan unas cosas sobre el FC o esperemos a la actualización por si sigue éste problema.
Saludos.

**Comment by asirena** [comment]
Lo del fallo yo ya no puedo reproducirlo (por haber cambiado el idioma a inglés para aceptar las condiciones). Si sabes como encontrar el mensaje (esperaba verlo en YellowPage, pero no lo he encontrado), o recuerdas a que se debía el mismo fallo en la Galería (al menos en todos los Mi Note 2 con la ROM que traen por defecto: la 5.10.16 creo que es).

Yo estoy convencido de que tiene que ser por el mensaje de aceptación, ya que al intentar mostrarlo da el FC mientras que en otro idiomas si lo muestra bien. Y una vez aceptado y no existiendo la necesidad de mostrarlo, ya no vuelve a fallar.

**Comment by jamflux** [comment]
Seguiré indagando, solo que por estos días andaré ocupado por ahí hasta el lunes debido al trabajo.
Sin embargo creo que dejo el idioma muy bien actualizado gracias a tu feedback.
Ya tengo en mi celular todo actualizado, a ti te toca esperar a mañana, jiji.
Saludos amig@.

**Comment by Infante007** [comment]
@jamflux se agradece tu gran trabajo
Y espero mañana la actualización, buscaré fallos de idioma 😀

**Comment by jamflux** [comment]
Vale, muy bien.
Tambien puedes ayudar a corregir el idioma chino en la aplicación TeleService.apk
Así con las correcciones actualizo.
Saludos.

**Comment by jamflux** [comment]
Listo, arreglado.
Subida versión global.
Muchas gracias @asirena e @Infante007 por el trabajo.
Cierro el caso, y a la espera de la actualización.
