### ISSUE TITLE
Errores en Ajustes

### ISSUE THREAD

**Issue by asirena** [ingbrzy/MA-XML-7.0-SPANISH#123]
En Ajustes > Ajustes adicionales > Seguridad
* "Smart Lock": debería ser "Bloqueo inteligente"
* El subtexto de "Agentes de confianza": está sin traducir "View or deactivate trust agent"

En Ajustes > Ajustes adicionales > Almacenamiento
* "Montar almacenamiento USB": debería ser "Montar tarjeta SD" (se encuentra en el apartado de tarjeta SD).
* "Insertar almacenamiento USB": debería ser "Insertar tarjeta SD" (se encuentra en el apartado de tarjeta SD).
* "Mount USB storage": debería ser "Montar almacenamiento USB"
* "Connect USB storage": debería ser "Conectar almacenamiento USB"

En Ajustes > Ajustes adicionales > Botones
* "Automatically disable navigation buttons": debería ser "Desactivar automáticamente los botones de navegación"
* "Automatically disable navigation buttons whe using selected apps. Double tap any navigation button to re-enable": denería ser  "Desactiva automáticamente los botones de navegación al utilizar las aplicaciones seleccionadas. Una doble pulsación sobre cualquier botón de navegación los reactiva."

En Ajustes > Ajustes adicionales > Transferencia
* Al entrar aparece un aviso sin traducir.

**Comment by jamflux** [comment]
Lo revisaré tan pronto pueda. Saludos.

**Comment by jamflux** [comment]
Montar tarjeta SD no se podría cambiar porque muchos dispositivos MI no traen slot de tarjeta sd, así que se traduce de manera más general.
Indagaré en lo de los botones.

**Comment by jamflux** [comment]
Botones, listos!

**Comment by asirena** [comment]
Yo no tengo puesta tarjeta SD, y entonces dicha opción aparece en gris (como apagada). No veo por tanto el motivo de no poderlo traducir; simplemente esa opción no será usable en aquellos teléfonos que no permitan tarjetas SD o quizás en sus ROMs no aparezcan esas opciones.

El error es que existen dos opciones (en un MI Note 2, al menos): una para almacenamiento usando tarjeta SD y otro para almacenamiento conectando un dispositivo USB. Y sin embargo se ha querido llamar USB al uso de tarjeta SD mientras que la opción correspondiente a USB se ha dejado sin traducir.

Luego subo unas capturas para que se entienda mejor.

**Comment by asirena** [comment]
Aquí la captura: 

http://oi65.tinypic.com/209kp4m.jpg

He englobado en rojo cada opción por separado, subrayado en naranja las que se ha cambiado USB por SD erroneamente, y en verde las que USB es correcto pero se encuentran sin traducir.

Saludos.

**Comment by jamflux** [comment]
Solucionado para la próxima actualización.
