### ISSUE TITLE
Errores en app Cámara

### ISSUE THREAD

**Issue by asirena** [ingbrzy/MA-XML-7.0-SPANISH#126]
En las opciones:

* "Degradado" debería ser "Enderezar" (no supone hacer ningún degradado en la imagen, sino evitar inclinaciones).

* "Cuenta atrás" debería ser "Temporizador"

**Comment by jamflux** [comment]
Corregidos errores para la próxima entrega de la ROM .eu

**Comment by asirena** [comment]
Gracias!
