### ISSUE TITLE
Errores en app Galeria

### ISSUE THREAD

**Issue by asirena** [ingbrzy/MA-XML-7.0-SPANISH#127]
* Al eliminar una foto aparece el mensaje en inglés: "Delete this photo from **** album (all devices)?"

* En las opciones de los albumen que no son los genéricos: "Turn on automatic backups"

* Al cambiar la opción del punto anterior el menaje tampoco está traducido: "Sync", "Turn on sync first" y "Go to Settings"

* En algunos albumes aparecen opciones sin traducir en la visualización de fotos/vídeos: "Delete", "Add to album", y "Details"

**Comment by jamflux** [comment]
Corregidos errores para la próxima entrega de la ROM .eu

**Comment by asirena** [comment]
Gracias!
