### ISSUE TITLE
Error de traducción en correo nativo 

### ISSUE THREAD

**Issue by Infante007** [ingbrzy/MA-XML-7.0-SPANISH#128]
Pone Print en vez de imprimir. 
Muchas gracias

**Comment by jamflux** [comment]
Lo revisaré entonces.

**Comment by Infante007** [comment]
no es nada importante pero por tener una rom completamente traducida ,aunque el curro te lo pegas tu ,muchas gracias @jamflux

**Comment by jamflux** [comment]
Arreglado, añadida línea.

**Comment by Infante007** [comment]
gracias compañero @jamflux
