### ISSUE TITLE
Error en app Mensajes

### ISSUE THREAD

**Issue by asirena** [ingbrzy/MA-XML-7.0-SPANISH#129]
Si abrimos un SMS (quizás con los MMS también, pero no los uso) cualquiera dentro de la aplicación y dejamos pulsado sobre el texto, aparecen 4 opciones abajo. La primera de ellas dice "Adelante", cuando debería ser "Reenviar" ya que crea un mensaje nuevo con el mismo texto listo para enviarlo.

**Comment by jamflux** [comment]
Muchas gracias @asirena.
Corregido.
