### ISSUE TITLE
Error en app Transferencia

### ISSUE THREAD

**Issue by asirena** [ingbrzy/MA-XML-7.0-SPANISH#130]
El mensaje de aviso de la necesidad de conexión está sin traducir: http://oi68.tinypic.com/1035puw.jpg

PD: He buscado las cadenas del mensaje en https://github.com/ingbrzy/MA-XML-7.0-SPANISH/blob/master/Spanish/main/Transfer.apk/res/values-es/strings.xml y no las encuentro. ¿Quiere esto decir que esos mensajes están en otra ubicación? Esto podría aclarar un poco el otro asunto de YellowPage.

**Comment by jamflux** [comment]
Voy a buscar la responsable...

**Comment by jamflux** [comment]
Estaba en la aplicación Backup.
Corregido.
Espero más errores, jeje.
Saludos.
