### ISSUE TITLE
VoLTE enabled/Use VoLTE to improbe voice and video call quality

### ISSUE THREAD

**Issue by Pab69** [ingbrzy/MA-XML-7.0-SPANISH#132]
Hola, en la última Rom EU Semanal aparece este parámetro en inglés:

 Configuración/Tarjetas SIM y redes móviles/VoLTE enabled/Use VoLTE to improbe voice and video call quality.

En Configuración Wi-Fi debajo de la red conectada pone: Pressione para compartir contraseña en vez de "Presione"

Había otra cosa que vi nada más instalar la rom que estaban todos los parámetros en inglés pero ahora no doy con ello.

Saludos!

**Comment by Pab69** [comment]
Me olvidé decir, el móvil es un Mi4c, Rom 6.4.28

**Comment by asirena** [comment]
También en Configuración/Tarjetas SIM y redes móviles:

* "Data roaming" en lugar de "Datos roaming" o simplemente "Roaming"
* "Mobile networks" en lugar de "Redes móviles" (en tres sitios: opción, título del apartado, y dentro de la opción).

**Comment by jamflux** [comment]
Arreglado ayer, pero VoLTE está bien, no tiene traducción.
Es como el servicio VoIP.

**Comment by Pab69** [comment]
Sí, además se escribe así: VoLTE

Gracias!
