### ISSUE TITLE
recompile issue!

### ISSUE THREAD

**Issue by ingbrzy** [ingbrzy/MA-XML-7.0-SPANISH#134]
W: /home/roms/miui_v5/wip/rom_wip_virgo/d_apks/CleanMaster.apk/res/values-es/strings.xml:121: error: Apostrophe not preceded by \ (in The file doesn't support to add to exceptions)
W: 
W: /home/roms/miui_v5/wip/rom_wip_virgo/d_apks/CleanMaster.apk/res/values-es/strings.xml:167: error: Apostrophe not preceded by \ (in Deleting delta updates won't influence app usage)
eh
: /home/roms/miui_v5/wip/rom_wip_virgo/d_apks/CloudService.apk/res/values-es/strings.xml:256: error: Multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?
W: 
W: /home/roms/miui_v5/wip/rom_wip_virgo/d_apks/CloudService.apk/res/values-es/strings.xml:258: error: Unexpected end tag string
: /home/roms/miui_v5/wip/rom_wip_virgo/d_apks/FileExplorer.apk/res/values-es/strings.xml:166: error: Apostrophe not preceded by \ (in Can't encrypt files in folder /MIUI/Gallery/cloud/sharer. Move files to another directory and try again.)
W: 
W: /home/roms/miui_v5/wip/rom_wip_virgo/d_apks/FileExplorer.apk/res/values-es/strings.xml:171: error: Apostrophe not preceded by \ (in Can't open file. Copy file to internal storage first.)
W: 
W: /home/roms/miui_v5/wip/rom_wip_virgo/d_apks/FileExplorer.apk/res/values-es/strings.xml:260: error: Apostrophe not preceded by \ (in Couldn't load sticker)
W: 
W: /home/roms/miui_v5/wip/rom_wip_virgo/d_apks/FileExplorer.apk/res/values-es/strings.xml:480: error: Apostrophe not preceded by \ (in Can't connect to the network.)
W: 
W: /home/roms/miui_v5/wip/rom_wip_virgo/d_apks/FileExplorer.apk/res/values-es/strings.xml:481: error: Apostrophe not preceded by \ (in Thank you for your feedback! We'll follow up as soon as possible.)
W: 
W: /home/roms/miui_v5/wip/rom_wip_virgo/d_apks/FileExplorer.apk/res/values-es/strings.xml:482: error: Apostrophe not preceded by \ (in Couldn't connect to server.)

**Comment by jamflux** [comment]
Sorry for this issue, now solved.

**Comment by jamflux** [comment]
Possible to add to @asirena to the master too?, he/she is active and can help us a lot.
Thank you @ingbrzy.

**Comment by ingbrzy** [comment]
added @asirena
