### ISSUE TITLE
Errores en app Seguridad

### ISSUE THREAD

**Issue by asirena** [ingbrzy/MA-XML-7.0-SPANISH#135]
Dice raíz en lugar de root en varios sitios.

Lo he cambiado: https://github.com/asirena/MA-XML-7.0-SPANISH/blob/e9865c31e23aa8cb897715b31c1c5a20904267b3/Spanish/main/SecurityCenter.apk/res/values-es/strings.xml y dejado propuesto para aceptación (líneas 35 - 37).

**Comment by jamflux** [comment]
Arreglado por petición.

**Comment by jamflux** [comment]
Hola @asirena. El administrador de xiaomi.eu te dio entrada oficial al grupo de traductores para que podamos seguir actualizando nuestro idioma.
yo le pedí el favor que te agregara porque los que habían antes no se han vuelto a conectar y como haz visto soy el único que aporto en las traducciones y una ayuda nunca está de más.
Lo errores que veas los vas corrigiendo por favor.
Hay una tarea pendiente con la aplicación galería, pronto subo las líneas que faltan por si nos puedes ayudar.
Mil gracias.



Enviado desde mi teléfono MiEl asirena <notifications@github.com>, 3/5/2016 7:09 escribió:Dice raíz en lugar de root en varios sitios.

Lo he cambiado: https://github.com/asirena/MA-XML-7.0-SPANISH/blob/e9865c31e23aa8cb897715b31c1c5a20904267b3/Spanish/main/SecurityCenter.apk/res/values-es/strings.xml y dejado propuesto para aceptación (líneas 35 - 37).
