### ISSUE TITLE
error en Spanish/main/Settings.apk/res/values-es/strings.xml

### ISSUE THREAD

**Issue by NeoDaemon** [ingbrzy/MA-XML-7.0-SPANISH#136]
Hola, hace un rato le pedi a ingbrzy por el foro de xiaomi.eu que hiciera una correccion que hace que el menu de fingerprints no se abra, pero al parecer corrigio una linea equivocada:
Se corrigio esta:

` -    <string name="add_fingerprint_text">Añadir huella dactilar</string>`
`+    <string name="add_fingerprint_text">"Huella "</string>`

Cuando debio ser esta

`<string name="fingerprint_list_title">Huella dactilar</string>`

a

`<string name="fingerprint_list_title">Huella </string>`

El error pasa (paso en la traducción francesa) porque al parecer no acepta 16 caracteres cuando crea una huella y por defecto las va llamando Huella dactilar1 y así sucesivamente, por lo cual al intentar entrar en las opciones de esa huella se queda en blanco la pantalla y vuelve atrás. Cuando pones la traducción en ingles esto no pasa, puedes acceder a las huellas creadas con nombre en ingles.

Igual me he confundido, pero es lo que he llegado a entender.

Un saludo y gracias por el trabajo con la rom de xiaomi.eu, que tanto nos sirve a muchos!

**Comment by jamflux** [comment]
Ya lo corregí, pídele a ver si resube las ROMs, jeje.
