### ISSUE TITLE
Fallo mio ,yo mismo cerre el post 137

### ISSUE THREAD

**Issue by Infante007** [ingbrzy/MA-XML-7.0-SPANISH#139]
Buenas, después de una semana sin actualizar por problemas con la version cacro. 
Vi muchas mejoras en la traduccion, pero vi algunas otras. 
![screenshot_2016-05-06-23-45-18_com miui gallery_1462572174814](https://cloud.githubusercontent.com/assets/18089036/15087414/d0fa71fc-13e8-11e6-9884-3186b60c8fd1.jpg)
![screenshot_2016-05-06-23-49-18_com android settings_1462572105960](https://cloud.githubusercontent.com/assets/18089036/15087422/da0e301c-13e8-11e6-9562-a77b6deeac0c.jpg)
![screenshot_2016-05-06-23-49-24_com android settings_1462572076811](https://cloud.githubusercontent.com/assets/18089036/15087426/e206b2e4-13e8-11e6-8b86-7697a91fa54b.jpg)
![screenshot_2016-05-06-23-37-20_com miui gallery_1462571595927_1462572044144](https://cloud.githubusercontent.com/assets/18089036/15087427/ea7d9b4a-13e8-11e6-9d16-37ea8e009482.jpg)
![screenshot_2016-05-06-23-45-25_com miui gallery_1462571663688_1462571996707](https://cloud.githubusercontent.com/assets/18089036/15087430/f1f61ba4-13e8-11e6-83df-a5e77cb9dbd0.jpg)
![screenshot_2016-05-06-23-44-44_com miui gallery_1462571747055_1462571976235](https://cloud.githubusercontent.com/assets/18089036/15087433/f7684e54-13e8-11e6-81b2-e4a9cd392269.jpg)
![screenshot_2016-05-06-23-44-16_com miui gallery_1462571782444_1462571946108](https://cloud.githubusercontent.com/assets/18089036/15087434/fc619cbc-13e8-11e6-96be-91498f6b02ca.jpg)
![screenshot_2016-05-06-23-48-38_com android settings_1462571906729](https://cloud.githubusercontent.com/assets/18089036/15087436/00fe0684-13e9-11e6-82fd-1faab7b13a84.jpg)
![screenshot_2016-05-06-23-40-03_com android settings_1462571878972](https://cloud.githubusercontent.com/assets/18089036/15087439/05e859a6-13e9-11e6-8c80-bc5254138ff4.jpg)
![screenshot_2016-05-06-23-38-16_com miui gallery_1462571838346](https://cloud.githubusercontent.com/assets/18089036/15087441/0b3f8956-13e9-11e6-80d4-0eaa50a782cb.jpg)

Gracias

Y en seguridad para aplicaciones
![screenshot_2016-05-07-15-59-01_com amazon mshop android shopping_1462629689681](https://cloud.githubusercontent.com/assets/18089036/15092531/30e82882-146d-11e6-97fd-736872aed0ae.jpg)
![screenshot_2016-05-07-16-00-02_com miui securitycenter_1462629731379](https://cloud.githubusercontent.com/assets/18089036/15092533/364ec02e-146d-11e6-9065-e2595481d1a0.jpg)
![screenshot_2016-05-07-16-00-07_com miui securitycenter_1462629711826](https://cloud.githubusercontent.com/assets/18089036/15092536/3b4d1292-146d-11e6-9846-97184aa65382.jpg)

en privacidad:
![screenshot_2016-05-07-17-05-27_com android settings_1462634068166](https://cloud.githubusercontent.com/assets/18089036/15092889/3901b786-1477-11e6-87c2-a7270ef45842.jpg)
![screenshot_2016-05-07-17-05-33_com android settings](https://cloud.githubusercontent.com/assets/18089036/15092892/3ea0167e-1477-11e6-9de5-60ab531e2373.png)

**Comment by Infante007** [comment]
En el navedor nativo también hay algunas más. 
![screenshot_2016-05-07-23-52-44_com android browser_1462658217810](https://cloud.githubusercontent.com/assets/18089036/15094768/83dc5620-14af-11e6-986d-ce9313ecef31.jpg)
![screenshot_2016-05-07-23-53-15_com android browser_1462658160598](https://cloud.githubusercontent.com/assets/18089036/15094769/8ae41f84-14af-11e6-83cb-41b493de6950.jpg)
![screenshot_2016-05-07-23-53-23_com android browser_1462658132895](https://cloud.githubusercontent.com/assets/18089036/15094772/906f1152-14af-11e6-9d1d-d22ff3740ee4.jpg)

**Comment by jamflux** [comment]
Hola @Infante007 
Era un poco obvio que hayan líneas sin traducir, son las nuevas de la semana y no da el tiempo de editar. Gracias por la estupenda labor de informar. Trabajaré en lo faltante.
Saludos.

**Comment by jamflux** [comment]
+La galería y el centro de seguridad arreglado. 
-2da y 3ra imagen no tengo idea de la app esa de pago, dame más detalles.
-En ajustes hay nuevos añadidos, debo conseguirlos antes del repositorio original, y eso tarda algo.
-Navegador y encriptación tienen nuevos añadido. Dame más detalles de cómo llegas a la encriptación porque no tengo idea.

Siempre que puedas dame la ruta de las capturas, hay unas que no son tan evidentes de sabes qué apps son.

Muchas gracias por tu dedicación en reportar errores de traducción.
Ojalá hubiese más personas como tú y también que se conectaran más traductores y no sólo yo :(

**Comment by jamflux** [comment]
Arreglado asunto del navegador gracias a @deivids84

**Comment by Infante007** [comment]
Gracias @jamflux ,me gustaria ayudar pero yo de ingles poco asi que joderia mas que ayudar,
la segunda imagen es el pago por nfc lo tengo activado para pagar por telefono (configuracion-mas-presionar y pagar) esa parte esta sin traducir entera.
Lo de la encriptacion esta en configuracion-ajustes adicionales-privacidad
Intentare a partir de la siguiente actualizacion poner las rutas en vez de fotos, (ademas de engorroso yo creo que sera mejor como tu dices),
y si es cierto que que al final tu trabajo como traductor al final no esta pagado.
Yo ayudare en lo que pueda.
un saludo

**Comment by jamflux** [comment]
Pues está muy bien que pongas las fotos, porque me ayuda a saber exactamente qué es lo que está en inglés.
Dime qué versión de xiaomi.eu tienes en tu celular, porque las traducciones faltantes en ajustes no las tengo en mi celular, esto respecto a privacidad y device storage.
La aplicación NFC no está incluida en el repositorio en español por eso no podría traducirla, pero sí podría agregarla si me pasas esa app.
No es tanto el pago de lo que hago, digo es que ya hace más de un mes soy, con ingbzry, el único que hace cambios y ayuda en la traducción de miui, no sé qué ha pasado con los demás traductores.

**Comment by Infante007** [comment]
OK , @jamflux como te comente ayudare en lo que yo pueda ,si controlara mas el ingles ayudaría sin problema.
Con las traducciones pues como pasa con todo ,las gente se cansa de ayudar por  no recibir nada a cambio ni siquiera un gracias por tu trabajo .
Estuve mirando la aplicación de pago y es la de mi banco BBVA WALLET , así que si no quieres complicarte que le den a esa parte de la traducción.
un abrazo y gracias por tu ayuda

**Comment by jamflux** [comment]
Bueno, cierro el caso porque ya las traducciones están listas.
Te pongo capturas de pantalla de los errores solucionados.
Lo siguiente es esperar a ingbzry para que genere las próximas ROMs con la actualización del español.

**Comment by jamflux** [comment]
Añadí las líneas faltantes al repositorio del Español en cuanto al teléfono cranco. Porque en mi hennessy no tenía ese menú para traducir.
Saludos.
