### ISSUE TITLE
Otra cosa, en la aplicación de correo nativo

### ISSUE THREAD

**Issue by Infante007** [ingbrzy/MA-XML-7.0-SPANISH#141]
Lo siento lo vi hoy y no me di cuenta. 
![screenshot_2016-05-09-10-28-55_com android email_1462783413403](https://cloud.githubusercontent.com/assets/18089036/15107943/5e211bd0-15d3-11e6-9532-6f59ffb68cef.jpg)
![screenshot_2016-05-09-10-29-05_com android email_1462783393667](https://cloud.githubusercontent.com/assets/18089036/15107947/62bd3f8e-15d3-11e6-8385-f6786be940f7.jpg)

**Comment by jamflux** [comment]
No encontré la segunda parte, la primera ya está traducida.
Deberás pasarme tu app de email para que pueda añadir esas líneas. Si puedes sube a zippyshare.com
Saludos.

**Comment by Infante007** [comment]
el teléfono no lo tengo rooteado por tema de la aplicación que me permite pagar por teléfono. Así que no puedo pasarte la aplicación.
Aunque ahora que lo veo ..... yo tengo dos correos ,el mío gmail y el de mi trabajo.
y entrando en ajustes-correo gmail-opciones de sincronización (hay viene el testo sin traducir como aparece en la segunda foto ) y si entras en opciones de sincronización también esta sin traducir Sent .
y entrando en ajustes-correo del trabajo -opciones de sincronización (hay también esta el testo son traducir como aparece en la segunda foto) y entrando en opciones de sincronización también estaba sin traducir folders (pero eso según me dices ya esta traducido por ti)

**Comment by jamflux** [comment]
No podría ayudarte si no me pasas la app.
Hay una aplicación en la tienda, se llama apk extractor, extrae las apps sin fallos y sin root.
En mi teléfono no tengo problemas con el email.

**Comment by Infante007** [comment]
ok ,ahora por seguridad, si te mando la apk de correo te mando solo la aplicacion o este programa te manda tambien los datos de mi correo y contraseñas?
gracias @jamflux

**Comment by jamflux** [comment]
Nop, manda sólo la app sin datos.No hay riesgo.

**Comment by jamflux** [comment]
Cierro el caso porque no existe el error de traducción en las nueva versión en mi teléfono. Dado el caso de no tener la app con errores para añadir al repositorio, cierro entonces.
