### ISSUE TITLE
Fallos en actualizacion

### ISSUE THREAD

**Issue by Infante007** [ingbrzy/MA-XML-7.0-SPANISH#142]
Hola otra vez @jamflux , vengo a molestar otro poquito mas.
Al conectar el usb al ordenador Viene en ingles. y luego las opciones también.
![screenshot_2016-05-13-10-05-56_com android settings](https://cloud.githubusercontent.com/assets/18089036/15241873/0b2c959e-18f3-11e6-9bb8-fefc0d6aa63c.png)

En la aplicación cámara viene Degradado , seria Enderezar y Centa atrás seria Temporizador

![screenshot_2016-05-13-09-45-19_com android camera_1463126571202](https://cloud.githubusercontent.com/assets/18089036/15241899/3935f7aa-18f3-11e6-9e0d-fb88d49d922c.jpg)

En configuración-ajustes adicionales-espacio de almacenamiento-pone device store

![screenshot_2016-05-13-09-48-26_com android settings_1463126615704](https://cloud.githubusercontent.com/assets/18089036/15241936/5cc46404-18f3-11e6-929c-041a25309b2d.jpg)

En configuración-privacidad-esta sin traducir lo de encriptación y dentro de dicha opcion

![screenshot_2016-05-13-09-47-51_com android settings_1463126650157](https://cloud.githubusercontent.com/assets/18089036/15241958/867d072e-18f3-11e6-86de-a6a5c67bb1f0.jpg)

![screenshot_2016-05-13-10-16-50_com android settings](https://cloud.githubusercontent.com/assets/18089036/15242050/05787a68-18f4-11e6-8bfe-c40d949faeeb.png)

Aplicación Musica -ajustes

![screenshot_2016-05-13-09-50-08_com miui player_1463126588208](https://cloud.githubusercontent.com/assets/18089036/15241986/a912ef60-18f3-11e6-983d-4dbc3c1b2ffc.jpg)

Y en aplicación cámara al borrar foto aparece parte del texto en ingles.

![screenshot_2016-05-13-09-45-41_com miui gallery_1463126696014](https://cloud.githubusercontent.com/assets/18089036/15242010/c08ac078-18f3-11e6-8efb-a0a7702630b2.jpg)

como siempre gracias por tu ayuda y tu gran trabajo @jamflux

**Comment by jamflux** [comment]
He vuelto por un rato.
Ya arreglé lo de galería, música ya estaba hecho pero no han subido los cambios, lo de la cámara ya quedó listo.
Lo otro faltante en la privacidad, he metido los cambios la vez pasada, pero no se aplicaron y no se podrá a menos que ingbzry cambie de repositorio principal pues el que usa no contiene tus líneas en inglés y entonces no son recogidas las líneas en español.

Cierro el caso porque ya he hecho lo que estaba a mi alcance.
Saludos amigo.
