### ISSUE TITLE
Cambiar una palabra para que se encuadre mejor

### ISSUE THREAD

**Issue by ander13579** [ingbrzy/MA-XML-7.0-SPANISH#143]
La aplicación configuración no no tiene suficiente espacio para que se pueda ver la palabra ¿Podrías cambiarla por la palabra ajustes? No si sabrás pero en España se dice ajustes y no configuración
Gracias

**Comment by jamflux** [comment]
Listo amigo, gracias por informar.
Los cambios para la próxima actualización de xiaomi.eu
