### ISSUE TITLE
Seguridad

### ISSUE THREAD

**Issue by Infante007** [ingbrzy/MA-XML-7.0-SPANISH#144]
Seguridad-permisos
![screenshot_2016-05-13-12-00-08_com miui securitycenter_1463133740777](https://cloud.githubusercontent.com/assets/18089036/15244725/df74d708-1902-11e6-88ff-810dfa0d3f5b.jpg)

Y dentro de la opción hay zonas nuevas son traducir 

![screenshot_2016-05-13-12-03-21_com google android packageinstaller](https://cloud.githubusercontent.com/assets/18089036/15244744/fa383ef4-1902-11e6-9773-fddf2c9f8971.png)
![screenshot_2016-05-13-12-03-12_com google android packageinstaller](https://cloud.githubusercontent.com/assets/18089036/15244749/ffeee334-1902-11e6-94f4-d0346ec98e2a.png)
![screenshot_2016-05-13-12-03-03_com google android packageinstaller](https://cloud.githubusercontent.com/assets/18089036/15244757/06172596-1903-11e6-8f32-be15817acd4c.png)

Y en WiFi también encontré esto 

![screenshot_2016-05-13-23-03-12_com android settings_1463173430077](https://cloud.githubusercontent.com/assets/18089036/15261877/2d48ddce-195f-11e6-8504-23ab62977fa1.jpg)

Gracias

**Comment by jamflux** [comment]
Las nuevas traducciones ya las apliqué ese mismo día que salió la ROM, pero ingbzry no se esperó a que yo terminará y publicó la ROM sin las traduciones nuevas. Le gusta hacer las cosas súper rápido y siendo yo solo el único voluntario traductor no me dio el tiempo de terminar antes.

**Comment by Infante007** [comment]
jajaja ok ,pense que la nueva rom se cargo tu trabajo.
Te agradezco tu trabajo, 
un saludo @jamflux

**Comment by jamflux** [comment]
Pink text	Untranslateable string, array or plural - Has to be removed from xml! [Found in 1 file(s)]	

Checked (normal) Spanish MIUI7 (es) repository on Fri 20 May 2016 02:03:04

/home/translators.xiaomi.eu/scripts/languages/Spanish_7/Spanish/main/Email.apk/res/values-es/strings.xml
449:    <string name="mailbox_name_server_all_unread">No leídos</string>
450:    <string name="mailbox_name_server_drafts">Borradores</string>
451:    <string name="mailbox_name_server_inbox">Entrada</string>
452:    <string name="mailbox_name_server_junk">Basura</string>
453:    <string name="mailbox_name_server_outbox">Salida</string>
454:    <string name="mailbox_name_server_sent">Enviados</string>
455:    <string name="mailbox_name_server_starred">Destacados</string>
456:    <string name="mailbox_name_server_trash">Papelera</string>

Escribo por acá: las nuevas líneas de email no se pueden agregar, me dice debo borrar.

**Comment by jamflux** [comment]
Lo anterior ya fue corregido lo que se podía. En el cranco hay unas líneas que no tiene el repositorio en inglés de las .eu y ahí si no puedo hacer nada.
Saludos.
