### ISSUE TITLE
Correo nativo 

### ISSUE THREAD

**Issue by Infante007** [ingbrzy/MA-XML-7.0-SPANISH#146]
Buenas la vez. 

![screenshot_2016-05-13-15-26-50_com android email_1463150983861](https://cloud.githubusercontent.com/assets/18089036/15252251/4314eb7a-192d-11e6-8ab9-1ad9098e78ff.jpg)
![screenshot_2016-05-13-15-26-38_com android email_1463151020845](https://cloud.githubusercontent.com/assets/18089036/15252256/47b41ade-192d-11e6-8efd-671b8bb583d3.jpg)

**Comment by jamflux** [comment]
Yo busqué y busqué y no encontré nada al respecto.
Por eso te pido me mandes esa aplicación del email que tienes actualmente en tu dispositivo, puedes enviarla que no hay riesgo de privacidad si la extraes con un apkextractor.
Desde mi dispositivo  redmi note 3 mtk no veo esa falta de traducciones, por eso envía esa app.

**Comment by jamflux** [comment]
Ya quedaste incluido en los créditos por reportar fallos en traducciones ;)

**Comment by Infante007** [comment]
https://mega.nz/#!vsgl1IoI

**Comment by jamflux** [comment]
Listo @Infante007 
Gracias a la apk que me enviaste logré obtener las líneas sin traducir y aplicarlas al repositorio en español.
Subí la app con los cambios hechos por si la quieres poner en tu móvil de nuevo:
http://www63.zippyshare.com/v/6LANKD1t/file.html

Cierro el caso.
Saludos y gracias por tu ayuda.
