### ISSUE TITLE
Traducción estable 7.3.1.0 (KHCCNDD)

### ISSUE THREAD

**Issue by jasanchez72** [ingbrzy/MA-XML-7.0-SPANISH#148]
Hola a todos,
 
Antes que nada, daros las gracias por el trabajo que hacéis y perdonad si me equivoco de sitio a la hora de publicar.

Hace poco puse la última versión estable para el RedMi 1S y me he dado cuenta de que tiene algunas partes sin traducir. Me gustaría saber:

- Si hay correcciones de traducción, ¿cómo se instalan y donde se descargan?
- Si me decís cómo se hace, puedo intentar traducirlo yo mismo y colaborar con el proyecto.

Saludos,
José A.

**Comment by Infante007** [comment]
Pues @jamflux te lo agradecerá un montón, porque ahora el único que traduce es el y tiene mucho trabajo. Y mi fallo es el inglés y por eso no puedo ayudar mucho.

**Comment by jasanchez72** [comment]
Y para aplicar las correcciones de las traducciones como se hace, he visto que algunas de las que me fallan ya están corregidas.

**Comment by Infante007** [comment]
@jasanchez72 pues aquí se dan los fallos de traducción y @jamflux  es el mas activo en traducir y asi se van corrigiendo.
Espera que se pase @jamflux y te dira que hace falta para corregir los fallos en la traducción.
yo creo que también lo intentare  (tengo mi cuñado que maneja el ingles, intentare que me ayude)

**Comment by jamflux** [comment]
@jasanchez72, ayuda es lo que necesito.
Con las actualizaciones semanales salen nuevas líneas por traducir y otras por quitar... y yo solo... ay no! jajaja
Clona el repositorio, le haces  los cambios que creas necesarios a las apps y busca un botón que dice PULL REQUEST. Luego lo reviso y añado.
Saludos.

**Comment by jasanchez72** [comment]
Lo que aun no se hacer es aplicar las mejoras de traducción que ya se han
hecho (algún tutorial, please?)

**Comment by jamflux** [comment]
@jasanchez72 Clonas el repositorio "MA-XML-7.0-SPANISH" en tu cuenta, editas lo que creas necesario, por ejemplo si ves cosas en inglés, por ejemplo en la app "Backup.apk" ves en strings.xml esto: <string name="feature_title_account">Mi Account</string>, en esta parte sólo debes traducir al español el contenido en inglés entre **">INGLÉS O CHINO</string>**. En el caso anterior pondrías:
<string name="feature_title_account">Cuenta Mi</string>

Respetando siempre la mayúscula al inicio de la palabra siempre y cuando la original en inglés empiece por mayúscula. En el caso anterior hay dos palabras con mayúscula, también se respeta la segunda palabra con mayúscula.

En todos los casos, si la frase tiene una mayúscula, se pone ésta al principio. Si tiene dos, se pone igual en la traducción, es así en todos los casos, se debe respetar y colocar las mayúculas según la frase, ya que android detecta como error si no coincide el número de mayúsculas y da el famoso FC (force close) en las aplicaciones.

Para saber qué es lo nuevo que sale cada semana para traducir visitas este enlace:
https://github.com/Acid-miuipolskapl/v6-XML-Compare/commits/master
Elige sólo una lista de cambios y trabaja con ella, las demás las puedes ignorar porque en si son los mismos cambios sólo que ingbzry los separa pordispositivos.

Yo elijo siempre la HENNESSY que es la de mi teléfono redmi note 3 mtk.

Salen con un + y en verde las nuevas líneas, por cada app deberás abrirla y añadir según el orden que lleva. Y al terminar la apk en sí guardas los cambios.

Espero captes la idea y contribuyas con este particular voluntariado, jeje.
Saludos.

**Comment by marcosmanteca** [comment]
Hola buenas, quiero ayudar, pero ahora mismo valdria la pena, no se mucho ingles, pero para cosas faciles se de sobra, o traducir algun error tonto. Pero vale la pena en traducir ya v7? o es mejor esperar ya a traducir la v8. Quiero ayudar.

**Comment by jamflux** [comment]
Gracias @marcosmanteca, seria de mucha ayuda tu colaboración. Arriba puse una breve reseña Dr como traducir.
Con cada nueva actualización se eliminan lineas y se añadeb nuevas, en verdad es mucha tarea para uno solo.

**Comment by Infante007** [comment]
Puff intento ayudar @jamflux ,baje el programa que hace falta para empezar GitHub, (esta en ingles ,mal empezamos) ,descargue el archivo que dices  arriba y intento entender el programa , pero ni idea ,,,algun video tutorial o alguna otra forma de entenderlo?

**Comment by jamflux** [comment]
No es necesario instalar la app esa, es muy complicada de usar y nunca he podido actualizar algo, se queda sincronizando y ahí se queda... Siempre hago las cosas desde el navegador.
En ésta página miras lo nuevo:
https://github.com/Acid-miuipolskapl/v6-XML-Compare/commit/1683db445725824d73ea275f6fed43354d0afcab

Miras de que app se trata, como ya has clonado el repositorio buscas y añades lo nuevo.

**Comment by Infante007** [comment]
ok luego uego lo miro

**Comment by Infante007** [comment]
Nada ni de coña. perdona por la torpeza.
Intento entender lo que nos dices pero no consigo entenderlo.

**Comment by jamflux** [comment]
Cuando salga miui 8 vuelvo al ruedo con las traducciones, y adelante todo lo que más pueda, por ahora no me ha dado mucho el tiempo.
Esperemos que en este tiempo alguien haga algo, jeje.
Saludos.

**Comment by Infante007** [comment]
Pues me parece cojonudo ,tomate unas semanas de descanso, pero sigo diciendo lo mismo ,si me enseñas intentare ayudarte.
Ya me diras cuando tengas mas tiempo
un saludo

**Comment by jamflux** [comment]
Buscame en telegram como @Jamflux.
Y podemos estar en contacto y te voy diciendo qué hacer.
