### ISSUE TITLE
Algunas cosas no traducidas- Xiaomi.eu 6.5.19 dev  Redmi Note 3

### ISSUE THREAD

**Issue by marcosmanteca** [ingbrzy/MA-XML-7.0-SPANISH#150]
Hola, antes de todo, gracias a los traductores, en concreto tambien a jamflux, te sigo desde la comunidad de htcmania, gracias por tu trabajo. Te paso algunas cosas no traducidas, con el fin de ayudarte en la busqueda de estas:
Pone NotificaTIones en vez de Notificaciones.
![screenshot_2016-05-20-15-22-06_com miui home](https://cloud.githubusercontent.com/assets/11967463/15442693/071a791c-1ee3-11e6-8cd7-41f105c01b28.png)

Esa frase en ingles.
![screenshot_2016-05-20-23-26-08_com whatsapp](https://cloud.githubusercontent.com/assets/11967463/15442698/119b0dca-1ee3-11e6-968f-133ee1b23c65.png)

En mi opinion queda mejor "Opciones de desarrollo", en vez de programador, en android stock se nombra siempre así, ademas, en este caso pone las 2 cosas, mejor o una o otra.
![screenshot_2016-05-20-15-28-03_com android settings](https://cloud.githubusercontent.com/assets/11967463/15442700/1445fd1e-1ee3-11e6-9357-d5fa6b7e788c.png)

Y bueno luego lo del app switcher que han puesto nuevo en esta versión, se que hay cosas que no has podido traducir porque no te ha dado tiempo Ingbrzy.

Te repito, muchas gracias por todo y por tu aporte a la comunidad. Puedo echarte una mano cuando quieras a buscar cosas de estas, ya que me imagino que es mucho trabajo ademas de traducir, buscar las cosas nuevas que se implementan y no están traducidas.

Estoy dispuesto a ayudarte, si asi lo deseas te paso mi correo electronico.

Un saludo.

**Comment by jamflux** [comment]
Listo, corregido todo lo del caso.
Lástima que hasta el 17 de junio se verían los cambios en las .eu.
Sólo tengo el hennessy (redmi note 3 mtk) y en él cocino y genero las ROMs con las traducciones para otros dispositivos no puedo porque no los tengo, jeje. Saludos.

**Comment by marcosmanteca** [comment]
Pero desde ese dia que ha dicho estara miui 8 traducido al español?  Si se
tendra k traducir casi de cero no?
