### ISSUE TITLE
Sin traducir en rom 6.5.19

### ISSUE THREAD

**Issue by Infante007** [ingbrzy/MA-XML-7.0-SPANISH#151]
Hola @jamflux , mejoro mucho la rom con tus traducciones.
Partes si traducir:

En ajustes de datos-limite de datos & notificaciones , se puede cambiar el símbolo & por una y ?

![screenshot_2016-05-20-11-47-24_com miui securitycenter_1463737775554](https://cloud.githubusercontent.com/assets/18089036/15447318/b51e25c6-1f3e-11e6-9d74-674d1fcf840f.jpg)

 

en las opciones al conectar el teléfono en el ordenador sigue apareciendo en ingles y las opciones también

![screenshot_2016-05-20-10-26-33_com android settings_1463737048018](https://cloud.githubusercontent.com/assets/18089036/15447336/6d759eec-1f3f-11e6-85a5-33d24aca8cfa.jpg)

En la opción de mi drop aparece en ingles Choose files to send , Files y el texto que esta al final esta en ingles

![screenshot_2016-05-20-10-28-12_com android fileexplorer_1463737025950](https://cloud.githubusercontent.com/assets/18089036/15447338/825d0890-1f3f-11e6-8bc4-64e07bcda421.jpg)
![screenshot_2016-05-20-10-28-22_com android fileexplorer_1463737005548](https://cloud.githubusercontent.com/assets/18089036/15447340/892033aa-1f3f-11e6-8f7f-0f1f762cc359.jpg)

En batería y rendimiento en gestión de uso de batería en aplicaciones , aparece en el texto batteria ( la t repetida)

![screenshot_2016-05-20-10-30-12_com android settings_1463736898476](https://cloud.githubusercontent.com/assets/18089036/15447342/9643fefe-1f3f-11e6-9977-5d5a69d5d86e.jpg)

En privacidad aparece Smart lock

![screenshot_2016-05-20-10-31-15_com android settings_1463736868405](https://cloud.githubusercontent.com/assets/18089036/15447343/a2483742-1f3f-11e6-9596-dc36011d8a5a.jpg)

**Comment by marcosmanteca** [comment]
Excelente, podríamos trabajar juntos para ayudar en la traducción, de esta manera seria mas eficiente y jamflux va a tiro hecho sin tener que mirar lo que no está traducido.

**Comment by Infante007** [comment]
Si lo fácil es buscar los problemas de traducción, el coñazo es buscar las líneas y ir traduciendo las y hay esta @jamflux

**Comment by marcosmanteca** [comment]
Am, es que hablando desde mi ignoracia en esto, pensaba que se podía mediante el notepad por ejemplo dar a que buscase la String en concreto a traducir en ingles y el notepad++  automaticamente te decia donde estaba en concreto esa String que quieres traducir, la palabra o frase vamos.
Claro yo no entiendo, pensaba que era así y no había que buscar tanto, es que así lo hago cuando trabajo en programación web para ir rápido. Un saludo y gracias.

**Comment by asirena** [comment]
En general es así, pero como existen tantos ficheros diferentes, lo dificil es encontrar cual es el que contiene la línea...

He estado buscando el "Delete this photo..." y no he dado con el. Pensaba que estaría en "Galería", y no. En cambio si he corregido algunos otros errores que he ido viendo en los ficheros que miraba (por ejemplo algunos de MiDrop) mientras buscaba ese error.


@jamflux, ¿como podemos hablar por privado? A partid de ahora quizás pueda echar una mano más activamente, pero la verdad es que también estoy un poco perdido entre tanta aplicación :)

**Comment by jamflux** [comment]
Delete ya lo he arreglado, estaba el plurals de la app galería. Fusioné y añadí todas las líneas existentes.
Yo uso telegrama, escribirme a @Jamflux, te respondo tan pronto pueda.
Saludos.

**Comment by Infante007** [comment]
cojonudo, porque yo lo busque y no lo encontraba.
ahora estoy buscando lo que pusieron nuevo al cortar y luego copiar, 
pone pegar y opción a frases mas usadas (pero esto en ingles) y luego si le das a esta opción aparece en ingles,
estoy buscando en framework-res.apk  ,pero no veo nada

**Comment by jamflux** [comment]
Caso cerrado, jeje.
Smart Lock no se encuentra, así que pasa como la app de email, cosas que no existen en el repositorio en inglés.
