### ISSUE TITLE
Mi criterio

### ISSUE THREAD

**Issue by Infante007** [ingbrzy/MA-XML-7.0-SPANISH#152]
Sobre el tema de los tamaños creo que no esta bien puesto.
Si no es asi pues me lo dices .
Lo tamaños pùestos son 
XCH - EXTRA PEQUEÑO 
creo que seria XS-EXTRA PEQUEÑO
CH-PEQUEÑO 
SERIA S-PEQUEÑO
M-MEDIANO ESTA BIEN
G-GRANDE 
SERIA L-GRANDE
XG-EXTRA GRANDE SERIA
XL.MUY GRANDE
XXG-XXG
SERIA XXL-EXTRA GRANDE
![screenshot_2016-05-21-10-43-53_com android settings](https://cloud.githubusercontent.com/assets/18089036/15447665/3098e366-1f4a-11e6-8646-ee873e548dc2.png)
![screenshot_2016-05-21-10-43-55_com android settings](https://cloud.githubusercontent.com/assets/18089036/15447667/3298d8a6-1f4a-11e6-8ce1-84ad3787c56c.png)
![screenshot_2016-05-21-10-43-58_com android settings](https://cloud.githubusercontent.com/assets/18089036/15447668/34630f1c-1f4a-11e6-9711-c1c30e749cd1.png)
![screenshot_2016-05-21-10-44-00_com android settings](https://cloud.githubusercontent.com/assets/18089036/15447670/36851dbc-1f4a-11e6-803c-305cab2a8b1a.png)
![screenshot_2016-05-21-10-44-03_com android settings](https://cloud.githubusercontent.com/assets/18089036/15447672/38a5cfec-1f4a-11e6-908d-cdca1327ee34.png)
![screenshot_2016-05-21-10-44-05_com android settings](https://cloud.githubusercontent.com/assets/18089036/15447673/3ac8caae-1f4a-11e6-9018-fffa586c305a.png)

**Comment by jamflux** [comment]
Muy buen trabajo.
No me ha dado el tiempo de entrar a github.

**Comment by Infante007** [comment]
No perdona @jamflux  , no hice ningun cambio porque todavia no manejo el github, te decia si no era mejor ponerlo asi.
gracias

**Comment by Infante007** [comment]
Cerrado
