### ISSUE TITLE
Aplicar mejoras de traducción

### ISSUE THREAD

**Issue by jasanchez72** [ingbrzy/MA-XML-7.0-SPANISH#168]
Hola,

Perdón por la torpeza, pero a día de hoy aun no sé como aplicar las mejoras de traducción que se han hecho en una ROM estable que tiene fallos.

¿Tengo que esperar a que salga la siguiente estable? ¿Cómo puedo saber si se han solucionado? Es que no me interesa ir instalando versiones semanales.

Gracias y un saludo,
José A.

**Comment by jamflux** [comment]
Hola @jasanchez72
Nosotros acá sólo nos dedicamos a traducir las partes que aparecen en inglés cada semana. Tratamos de mantener al día el asunto de las correciones de las traducciones.
Cuando sale una nueva versión de ROM no da el tiempo suficiente para aplicar los nuevos cambios ese mismo día antes de que xiaomi.eu genere y agregue idiomas a sus ROMs.

Acá somos muy pocos (3 personas actualmente) que colaboramos de manera voluntaria con las traducciones. Siempre estoy muy al pendiente de quién quiere ayudar y enseñarle lo poco que sé.

Las ROMs en sí no las generamos nosotros, las genera @ingbrzy cada semana para las ROMs betas y las estables cada mes.

Yo genero mis porpias ROMs pero para mi teléfono que es el redmi note 3 mtk y las publico en el subforo de htcmanía.com.

Saludos.
