### ISSUE TITLE
Pequeños fallos encontrados (Redmi 1S)

### ISSUE THREAD

**Issue by ilopez85** [ingbrzy/MA-XML-7.0-SPANISH#88]
Spanish/main/framework-miui-res.apk/res/values-es-rES/strings.xml:
===============================================================================
En opciones de selección la etiqueta de "Pegar" aparece desalineada, es posible que los textos de "Seleccionar" y "Seleccionar todo" sean demasiado largos teniendo en cuenta el número de caracteres en inglés: Seleccionar (11) vs Select (6) y Seleccionar todo (16) vs Select all (10), creo que sustituir Seleccionar por Selec. (abreviado) en ambos casos solucionaría el problema.

![screenshot_2015-10-27-08-59-12](https://cloud.githubusercontent.com/assets/2221936/10752812/ea8538d0-7c8c-11e5-8ea9-abd71d9196ee.png)

Spanish/main/MiuiGallery.apk/res/values-es/strings.xml:
===============================================================================
En el mensaje de "Aviso de Red" aparecen dos variables que se supone deberían haber sido sustituidas por cadenas de texto.

![screenshot_2015-10-26-16-22-04](https://cloud.githubusercontent.com/assets/2221936/10734190/46a1bbce-7c02-11e5-9ee1-82d077fe834a.png)

Spanish/main/Mms.apk/res/values-es/strings.xml:
===============================================================================
Dentro de las opciones de la aplicación aún aparece "Message" sin traducir en dos ocasiones.

![screenshot_2015-10-26-16-38-33](https://cloud.githubusercontent.com/assets/2221936/10734195/534e7466-7c02-11e5-8fdf-ec9536012554.png)

Spanish/main/Settings.apk/res/values-es/strings.xml:
===============================================================================
Dentro de WiFi en Ajustes avanzados Wi-Fi, "certificado" aparece escrito con mayúscula en una línea, y en minúscula en la siguiente (es una chorrada, pero queda relativamente "feo").

![screenshot_2015-10-26-16-27-18](https://cloud.githubusercontent.com/assets/2221936/10734205/5a78d592-7c02-11e5-9d7b-59da7353afd2.png)

**Comment by ilopez85** [comment]
Acabo de compilar la rom de nuevo con las correcciones del día 30 (gracias por incluirlas) y estos son los resultados:

SOLUCIONADO:
Spanish/main/framework-miui-res.apk/res/values-es-rES/strings.xml
Spanish/main/Settings.apk/res/values-es/strings.xml

AÚN PRESENTE:
Spanish/main/MiuiGallery.apk/res/values-es/strings.xml
Spanish/main/Mms.apk/res/values-es/strings.xml

**Comment by elyorch76** [comment]
He sustituido Seleccionar todo por Selec. todo. A ver si con eso vale.

Certificado corregido.

Spanish/main/MiuiGallery.apk/res/values-es/strings.xml Lo he revisado y la traducción está bien. La sustitución de las variables la hace el sistema. Yo ahí no puedo hacer nada.

Spanish/main/Mms.apk/res/values-es/strings.xml He hecho todo lo contrario, poner todo como Mi Message, puesto que es un producto de Mi y lo he dejado con su nombre original, como Mi Cloud.

**Comment by ilopez85** [comment]
"He sustituido Seleccionar todo por Selec. todo. A ver si con eso vale."

![screenshot_2015-11-02-10-54-55](https://cloud.githubusercontent.com/assets/2221936/10878824/7b11930e-8150-11e5-9650-8bcdfba3b5b1.png)

"Certificado corregido."

![screenshot_2015-11-02-10-56-17](https://cloud.githubusercontent.com/assets/2221936/10878831/82b80eee-8150-11e5-8856-590120870bed.png)

"Spanish/main/MiuiGallery.apk/res/values-es/strings.xml Lo he revisado y la traducción está bien. La sustitución de las variables la hace el sistema. Yo ahí no puedo hacer nada."

Lo que sucede en este caso es un misterio sin resolver. Cuando me bajo el repositorio actualizado con los cambios, el texto aparece entrecomillado en el archivo xml correspondiente, en cambio, tras compilar de nuevo la apk de la galería, si la decompilo y abro dicho archivo, el texto aparece sin comillas ¿?. Por más vueltas que le doy no soy capaz de encontrar un motivo, lo he intentado varias veces, borrando los archivos locales y volviéndomelos a bajar, pero el resultado es inexplicablemente el mismo.

"Spanish/main/Mms.apk/res/values-es/strings.xml He hecho todo lo contrario, poner todo como Mi Message, puesto que es un producto de Mi y lo he dejado con su nombre original, como Mi Cloud."

Personalmente opino igual, creo que es mejor dejar todo lo relacionado con aplicaciones de MIUI con su nombre original (Mi Account, Mi Cloud, Mi Message, etc.) no sé porque algunas personas se empeñan en traducirlo, es como si nos empeñasemos en traducir Windows al castellano, que muy comercial no sería el nombre (Ventanas) la verdad xD.

**Comment by elyorch76** [comment]
Gracias, te recuerdo que tú también puedes trabajar en las traducciones. Yo empecé como tú, soy un simple usuario de MIUI. Y viendo que tú controlas de temas de compilaciones de los que yo no tengo ni idea... seguro que lo harías bien ;-)

Sólo tienes que pedirle a ingbrzy que te de acceso para editar en este repositorio.

**Comment by ilopez85** [comment]
Gracias, te recuerdo que tú también puedes trabajar en las traducciones. Yo empecé como tú, soy un simple usuario de MIUI. Y viendo que tú controlas de temas de compilaciones de los que yo no tengo ni idea... seguro que lo harías bien ;-)

Sólo tienes que pedirle a ingbrzy que te de acceso para editar en este repositorio.
===============================================================================

Gracias, la verdad es que ahora ando algo algo liado, quizá más adelante ;)

Spanish/main/MiuiGallery.apk/res/values-es/strings.xml:
===============================================================================

Al parecer las cadenas de texto que deberían sustituirse han desaparecido en el texto original, de ahí el error.

![screenshot_2015-11-09-01-06-15](https://cloud.githubusercontent.com/assets/2221936/11037771/de82a194-86ff-11e5-9530-399b23ca82c8.png)

Con eliminar la primera frase (la que contiene dichas variables) sería suficiente, con lo que quedaría:

Algunas características requieren conexión a internet para funcionar con normalidad.

**Comment by elyorch76** [comment]
Corregido.

Cualquier ayuda por pequeña que sea es bienvenida.
