### ISSUE TITLE
Mayuscula 

### ISSUE THREAD

**Issue by marcosmanteca** [ingbrzy/MA-XML-7.0-SPANISH#90]
Hola muy buenas, me he dado cuenta que después de cerrar todas la aplicaciones de una vez con la "X" la primera letra de "limpiados" está en minúscula.

![screenshot_2015-11-12-22-59-40_com teslacoilsw launcher](https://cloud.githubusercontent.com/assets/11967463/11134446/1f5bb904-899d-11e5-8a7f-711bb2423501.png)

Aquí por ejemplo esta correcto, con mayus al principio.

![screenshot_2015-11-12-22-59-24_com teslacoilsw launcher](https://cloud.githubusercontent.com/assets/11967463/11134469/3e0d0ab0-899d-11e5-825e-8c19556a6020.png)

Sé que es una pijada, pero ya que está quedando de cine la traducción de la rom xD.
Muchas gracias por tu trabajo, lo valoro mucho. Un saludo.

**Comment by elyorch76** [comment]
En inglés también está en minúscula y yo estoy de acuerdo, para mí queda bien. Por ejemplo, igual que en el pantallazo que pones "jue. 12 de noviembre"
