### ISSUE TITLE
Administrar uso de batería en chino

### ISSUE THREAD

**Issue by tmp-meteque** [ingbrzy/MA-XML-7.0-SPANISH#91]
Hola, desde la última versión semanal este menú sale en chino.

![photo_2015-11-13_10-43-21](https://cloud.githubusercontent.com/assets/773734/11143181/9d3d537c-89f3-11e5-9c3d-1b3ffd2aec47.jpg)

Está en Ajustes adicionales → Batería - Administrar uso de batería.

Gracias.

**Comment by elyorch76** [comment]
Corregido
