### ISSUE TITLE
Escritas en chino en la aplicación Búsqueda - 5.11.26

### ISSUE THREAD

**Issue by ghost** [ingbrzy/MA-XML-7.0-SPANISH#92]
![screenshot_2015-11-30-21-57-51_com android quicksearchbox](https://cloud.githubusercontent.com/assets/15057642/11484410/263d7a7c-97ae-11e5-8052-6237f56aa6f2.png)

**Comment by elyorch76** [comment]
Eso de momento no se puede traducir, lo siento

**Comment by fantakk** [comment]
Pero sipones el inglés no sale, de repente se podrá esconder? Gracias.

**Comment by elyorch76** [comment]
Pensaba que en inglés también salía, lo miraré

**Comment by elyorch76** [comment]
Corregido
