### ISSUE TITLE
Line busy en lugar de línea ocupada

### ISSUE THREAD

**Issue by specipez** [ingbrzy/MA-XML-7.0-SPANISH#93]
Hola, cuando una llamada es rechazada por la persona a la que llamas pone "Line busy" en lugar de "Línea ocupada".

Esto ocurre por lo menos en el mi4i.

Saludos

**Comment by elyorch76** [comment]
Corregido, no sé si saldrá en la ROM de mañana o en la de la semana que viene.

**Comment by specipez** [comment]
Perfecto muchas gracias! Son estos detalles los que marcan la diferencia!
