### ISSUE TITLE
Itinerancia Internacional

### ISSUE THREAD

**Issue by jlopezcrd** [ingbrzy/MA-XML-7.0-SPANISH#94]
No se puede activar la itinerancia internacional.

https://drive.google.com/file/d/0B6XKt95B3lOXbGtGc01LSHNHUXc/view?usp=sharing
https://drive.google.com/file/d/0B6XKt95B3lOXdzhsRXI5Qjk0Yjg/view?usp=sharing
https://drive.google.com/file/d/0B6XKt95B3lOXWko3SE5QTlA1RFU/view?usp=sharing

**Comment by elyorch76** [comment]
Si el problema es de funcionamiento... esto es sólo para traducciones. Lo que si voy a hacer es cambiar la traducción: "No usar servicios de datos en itinerancia" por "Conectar a servicios de datos en itinerancia". Este texto no cambia, es el mismo tanto si están conectados como si no.

**Comment by jlopezcrd** [comment]
Ok, muchas gracias, te voy a postear algunas cosas que me salen en chino, por si las puedes cambiar también.

¿Dónde podría preguntar por el tema de que no se activa? Gracias

**Comment by elyorch76** [comment]
En el foro
