### ISSUE TITLE
Menú sin traducción

### ISSUE THREAD

**Issue by specipez** [ingbrzy/MA-XML-7.0-SPANISH#95]
Hola, he encontrado un menú que sale todo en inglés, no esta traducido:

Ajustes/Más/Transmisiones móviles: y ahí sale todo en inglés tanto en SUB1 como en SUB2.

Esta en inglés tanto el título "cell broadcast settings" como las opciones.

Si puedes echarle un vistazo para el mi4i te lo agradecería porque no se muy bien para que sirven esas opciones.

Gracias.

**Comment by elyorch76** [comment]
Corregido

**Comment by specipez** [comment]
Gracias! No era poco trabajo !
