### ISSUE TITLE
Aplicación de múscia (Fuera de línea): etiquetas demasiado largas en barra de navegación

### ISSUE THREAD

**Issue by ilopez85** [ingbrzy/MA-XML-7.0-SPANISH#97]
Personalmente he sido incapaz de encontrar el origen del problema, las cadenas "tab_track", "tab_folder", ..., "tab_local_track_list", "tab_local_folder_list", ... están ya abreviadas, por lo que no sé de dónde puede proceder el error.

![screenshot_2015-12-25-14-34-12_com miui player](https://cloud.githubusercontent.com/assets/2221936/12003181/03a83e82-ab15-11e5-852b-387a302a303a.png)

**Comment by jamflux** [comment]
Arreglado, estaba en local_music label, se tradujo por fuera de línea.
