### ISSUE TITLE
Confirmación de password

### ISSUE THREAD

**Issue by umpire1982** [ingbrzy/MA-XML-7.0-SPANISH#98]
Al acceder al cambio de huella dactilar se pide confirmación de la contraseña/pin. El texto que aparece no es legible y contiene errores. 

![screenshot_2016-01-20-14-26-05_com android settings](https://cloud.githubusercontent.com/assets/16799068/12450202/6d88298a-bf82-11e5-8c1f-72c3e208ce34.png)

**Comment by jamflux** [comment]
With next update will be fixed, I hope so.
Pronto será arreglado este asunto de la traducción.
